---
abstract: 'Data object for navigation item.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Navigation-Item
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Mo: 0
  Mo::utils: 0.09
  Mo::utils::CSS: 0.02
  Mo::utils::URI: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Data-Navigation-Item/issues
  homepage: https://github.com/michal-josef-spacek/Data-Navigation-Item
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Data-Navigation-Item
version: '0.02'
